output_dir: output

samples: &samples
  GN2ej:
    path: '/home/randon_h/gnnej/gnn-plots/data/epoch=008-val_loss=0.02631__test_pp_output_val.h5'
    label: 'GN2ej'
    reference: True
    df_name: jets
  GN2ej_noPt:
    path: '/home/randon_h/gnnej/gnn-plots/data/epoch=008-val_loss=0.02631__test_pp_output_val.h5'
    label: 'GN2ej_noPt'
    reference: False
    df_name: jets

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [6, 6]
  use_atlas_tag: False
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  # roc:
    # class: plotter.plot_classes.roc_plot.RocPlotBase
    # samples: *samples
    # file_name: roc.png
    # target_label: isDisplaced
    # tagger_output: GN2ej_pdispjet
    # range: !!python/tuple [0.75, 1, 100]
    # style:
    #   <<: *style
    #   n_ratio_panels: 1
    #   ylabel: "QCD rejection"
    #   xlabel: "EJ efficiency"
    #   y_scale: 1.4

  vertex:
    class: plotter.plot_classes.vertex_plot.VertexPlotBase
    samples:
      path: '/home/randon_h/gnnej/gnn-plots/data/epoch=008-val_loss=0.02631__test_pp_output_val.h5'
      label: 'GN2ej sample'
      df_name: tracks_from_jet
    file_name: vertex_index.png
    jet_num: 1
    style:
      <<: *style
      figsize: !!python/tuple [6,6]
      xlabel: "$n_{track}$"
      ylabel: "$n_{track}$"
      show_entries: False
      show_percentages: False
      text_color_threshold: 0.6
      colormap: gray
      cbar_label: ""