output_dir: output

samples: &samples
  GN2ej:
    path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_6_20240611-T092345/ckpts/epoch=010-val_loss=0.02273__test_pp_output_val.h5'
    label: 'mc23-fold0 - 6 layers'
    reference: True
    df_name: jets
  GN2ej_noPt:
    path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_5_20240610-T113645/ckpts/epoch=008-val_loss=0.02312__test_pp_output_val.h5'
    label: 'mc23-fold0 - 5 layers'
    reference: False
    df_name: jets
  GN2ej_4:
    path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_4_20240611-T092747/ckpts/epoch=012-val_loss=0.02329__test_pp_output_val.h5'
    label: 'mc23-fold0 - 4 layers'
    reference: False
    df_name: jets
  GN2ej_3:
    path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_3_20240610-T114657/ckpts/epoch=009-val_loss=0.02301__test_pp_output_val.h5'
    label: 'mc23-fold0 - 3 layers'
    reference: False
    df_name: jets
  GN2ej_2:
    path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_2_20240611-T092747/ckpts/epoch=012-val_loss=0.02351__test_pp_output_val.h5'
    label: 'mc23-fold0 - 2 layers'
    reference: False
    df_name: jets

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [6.5, 6]
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0

plots:
  roc:
    class: plotter.plot_classes.roc_plot.RocPlotBase
    samples: *samples
    file_name: roc-layercompare.png
    target_label: isDisplaced
    tagger_output: GN2ej_pdispjet
    range: !!python/tuple [0.95, 1, 100]
    style:
      <<: *style
      n_ratio_panels: 1
      ylabel: "QCD rejection"
      xlabel: "EJ efficiency"
      y_scale: 1.4