output_dir: output

samples: &samples
  path: '/project/def-mdanning/rhall02/salt/salt/logs/mc23-fold0-gnn-count/GN3ej_20240613-T111915/ckpts/epoch=010-val_loss=0.02255__test_pp_output_val.h5'
  label: 'GN3ej'
  df_name: tracks

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [10, 5]
  use_atlas_tag: True
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  vertex:
    class: plotter.plot_classes.vertex_plot.VertexPlotBase
    samples: *samples
    file_name: jet20-VImat.pdf
    jet_num: 20
    zoom: True
    style:
      <<: *style
      figsize: !!python/tuple [10,5]
      xlabel: "$n_{track}$"
      ylabel: "$n_{track}$"
      show_entries: False
      show_percentages: False
      text_color_threshold: 0.6
      colormap: gray
      cbar_label: ""